# Generated by Django 5.2.9 on 2026-01-06 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slot", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_booking_per_user_and_slot",
        ),
    ]
