# Generated by Django 5.2.9 on 2025-12-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CO', 'CONFIRMED'), ('CA', 'CANCELLED')], max_length=2),
        ),
    ]
