# Generated by Django 5.2.9 on 2025-12-29 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_cinema_address_alter_cinema_city_and_more'),
        ('movie', '0003_alter_movie_genres_remove_movie_language_and_more'),
        ('slot', '0003_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_by_slot', to='slot.slot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slot',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_by_cinema', to='cinema.cinema'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_by_movie', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_by_booking', to='slot.booking'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_column',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_row',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'slot'), name='unique_booking_per_user_and_slot'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seat_row', 'seat_column', 'booking'), name='unique_seat_per_booking'),
        ),
    ]
