# Generated by Django 5.2.9 on 2026-01-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_city_options_alter_genre_options_and_more'),
        ('cinema', '0002_seat_remove_cinema_unique_cinema_at_each_address_and_more'),
        ('movie', '0004_alter_movie_options_alter_movie_duration_and_more'),
        ('slot', '0003_remove_booking_unique_booking_per_user_and_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='booking',
        ),
        migrations.RemoveConstraint(
            model_name='slot',
            name='slot_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='slot',
            name='unique_slot_per_cinema_and_movie',
        ),
        migrations.AddField(
            model_name='slot',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='base.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='cinema.cinema'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='movie.movie'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('cinema', 'start_time'), name='unique_slot_per_cinema_time'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
