# Generated by Django 5.2.9 on 2026-01-20 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('slot', '0003_remove_booking_unique_booking_per_user_and_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='language',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='slots_by_language', to='base.language'),
            preserve_default=False,
        ),
    ]
