# Generated by Django 5.2.9 on 2026-01-25 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_city_options_alter_genre_options_and_more"),
        ("cinema", "0003_seat_and_more"),
        ("movie", "0004_alter_movie_options_alter_movie_duration_and_more"),
        ("slot", "0004_slot_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="slot",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="booking",
        ),
        migrations.RemoveConstraint(
            model_name="slot",
            name="unique_slot_per_cinema_and_movie",
        ),
        migrations.AlterField(
            model_name="slot",
            name="cinema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="cinema.cinema",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="base.language",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="slots", to="movie.movie"
            ),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.UniqueConstraint(
                fields=("cinema", "start_time"), name="unique_slot_per_cinema_time"
            ),
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
