# Generated by Django 5.2.9 on 2026-01-07 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_profile_picture_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='Invalid Phone number', message='Phone number should be exactly 10 numeric digits', regex='^\\d{10}$')]),
        ),
    ]
