# Generated by Django 5.2.9 on 2026-01-25 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone_number",
                        message="Phone number should be exactly 10 numeric digits",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
