# Generated by Django 5.2.9 on 2026-01-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=125, unique=True)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('poster', models.CharField(max_length=255)),
                ('genres', models.ManyToManyField(related_name='movies_by_genre', to='base.genre')),
                ('language', models.ManyToManyField(related_name='movies_by_language', to='base.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
