# Generated by Django 5.2.9 on 2025-12-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='generes',
            new_name='genres',
        ),
    ]
