# Generated by Django 5.2.9 on 2026-01-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='language',
            new_name='languages',
        ),
    ]
