# Generated by Django 5.2.9 on 2025-12-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_generes_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies_by_genre', to='movie.genre'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=125, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.ManyToManyField(related_name='movies_by_language', to='movie.language'),
        ),
    ]
