# Generated by Django 5.2.9 on 2026-01-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_language_movie_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(help_text='HH:MM:SS'),
        ),
    ]
