# Generated by Django 5.2.9 on 2026-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_city_options_alter_genre_options_and_more'),
        ('movie', '0003_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(help_text='Format: HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='base.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='languages',
            field=models.ManyToManyField(related_name='movies', to='base.language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(db_index=True),
        ),
    ]
