# Generated by Django 5.2.9 on 2026-01-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('rows', models.PositiveSmallIntegerField()),
                ('seats_per_row', models.PositiveSmallIntegerField()),
                ('image', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='base.city')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'address'), name='unique_cinema_at_each_address')],
            },
        ),
    ]
