# Generated by Django 5.2.9 on 2026-01-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cinema",
            name="unique_cinema_at_each_address",
        ),
        migrations.AddConstraint(
            model_name="cinema",
            constraint=models.UniqueConstraint(
                fields=("name", "address", "city"),
                name="unique_cinema_at_each_address_and_city",
            ),
        ),
    ]
