# Generated by Django 5.2.9 on 2026-01-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_city_options_alter_genre_options_and_more"),
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveSmallIntegerField()),
                ("seat_number", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="cinema",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cinemas/"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="cinema",
            constraint=models.UniqueConstraint(
                fields=("name", "city", "address"), name="unique_cinema_location"
            ),
        ),
        migrations.AddField(
            model_name="seat",
            name="cinema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="cinema.cinema",
            ),
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("cinema", "row_number", "seat_number"), name="unique_seat_per_cinema"
            ),
        ),
    ]
