# Generated by Django 5.2.9 on 2025-12-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemas_by_city', to='cinema.city'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='rows',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='seats_per_row',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='cinema',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_cinema_at_each_address'),
        ),
    ]
