# Generated by Django 5.2.9 on 2026-02-01 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_seat_remove_cinema_unique_cinema_at_each_address_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cinema",
            name="unique_cinema_at_each_address",
        ),
    ]
